### ISSUE TITLE
 Retirement of legacy RCSB PDB APIs in November 2020

### ISSUE THREAD

**Issue by josemduarte** [ningyuansg/jPdbApi#4]
The RCSB PDB legacy APIs are going to be discontinued in November 2020, see the news article:

https://www.rcsb.org/news?year=2020&article=5eb18ccfd62245129947212a&feature=true

All programmatic users are strongly encouraged to migrate to the new APIs before November 2020.

New json-based APIs are now available that provide more comprehensive search and fetch capabilities, see https://www.rcsb.org/pages/webservices. Highlights include :

- A GraphQL interface for the Data API 
- Full boolean support for Search API
- Integrated text + scientific searches (structure search, sequence search) in the Search API

**Comment by ning-y** [comment]
Thanks for the notice!

**Comment by ning-y** [comment]
Fixed with 2b7927d.
